config/routes.rb
NewsClone::Application.routes.draw do
  resources :links
  resources :users
  resources :votes
  resources :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/link.rb
class Link < ActiveRecord::Base

  belongs_to :user
  has_many :votes
  has_many :users, through: :votes

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :links
  has_many :votes
  has_many :links, through: :votes

end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :link
  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @links = Link.all
    @vote = Vote.new
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      flash[:notice] = "Link was successfully created"
      redirect_to links_path
    else
      render 'new'
    end
  end

  private
  def link_params
    params.require(:link).permit(:name, :url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def new
    @vote = Vote.new
  end

  def create

    @vote = Vote.new(vote_params)
    if @vote.save
      flash[:notice] = "Vote was successfully counted"
      redirect_to links_path
    else
      render links_path
    end
  end

  private
  def vote_params
    params.require(:vote).permit(:user_id, :link_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewsClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>

  <%= flash[:alert] %>
  <%= flash[:notice] %>
</div>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f|%>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name , class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url , class: "form-control"%>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/links/index.html.erb
<h1>Links</h1>


<ul class="jumbotron">
  <% @links.each do |link| %>
    <li>
      <p><%= form_for(@vote) do |f| %>
        <% f.label :link_id %>
        <%= f.hidden_field :link_id, value: link.id %>
        <% f.label :user_id %>
        <%= f.hidden_field :user_id, value: 4 %>
        <%= f.submit(:class => "btn btn-primary", :value => "Up Vote") %>
        <a href ="<%= link.url %>"><%= link.name%></a>
      <% end %>
      </p>
    </li>
  <% end %>
</ul>


<%= link_to "New link", new_link_path, :class => "btn btn-default" %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render('form') %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>